### ISSUE TITLE
Error about missing operation 'div' in tikz

### ISSUE THREAD

**Issue by gwtaylor** [dukebw/ml-reading-notes-improved-system#1]
I'm getting this when I try to compile. I'm not a tikz user, so I'm a bit baffled. Did you encounter this?

```
./data/mutan-ours.tikz:264: Package PGF Math Error: Sorry, the operation 'div'
has not yet been implemented in the floating point unit (in '{-1-div(1,4)}').
```

**Comment by gwtaylor** [comment]
Interestingly, I had no problem compiling any of the tikz in the CRV paper.

**Comment by dukebw** [comment]
Hmm, I wonder if this is due to a difference in the version of PGF that we have. There is a StackOverflow question about this issue here: https://tex.stackexchange.com/questions/336520/tikz-math-div-error. It seems like the issue is something to do with switching the PGF floating point unit on.

I tried switching `div(\x, 4)` to `\x / 4` as someone suggested in the comments, but that changes the figure.

**Comment by gwtaylor** [comment]
I'm interested to know which version you have. Looks like I have 3.0.1a (2017-04-18). But now TexLive 2017 is frozen so I will need to do a complete update to bump up my packages. Will investigate when I have some more time to deal with it!

```
stgeorge:duke_vqa_hadamard gwtaylor$ tlmgr info pgf
TeX Live 2017 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
package:     pgf
category:    Package
shortdesc:   Create PostScript and PDF graphics in TeX
longdesc:    PGF is a macro package for creating graphics. It is platform- and format-independent and works together with the most important TeX backend drivers, including pdfTeX and dvips. It comes with a user-friendly syntax layer called TikZ. Its usage is similar to pstricks and the standard picture environment. PGF works with plain (pdf-)TeX, (pdf-)LaTeX, and ConTeXt. Unlike pstricks, it can produce either PostScript or PDF output.
installed:   Yes
revision:    44231
sizes:       src: 369k, doc: 14009k, run: 5261k
relocatable: No
cat-version: 3.0.1a
cat-date:    2017-04-18 05:31:40 +0200
cat-license: lppl1.3gpl2
cat-topics:  pgf-tikz graphics-in-tex
collection:  collection-pictures
```

**Comment by dukebw** [comment]
My version of PGF appears to be 3.0.1a as well. I did find that I was accidentally hiding a few figures with .gitignore so I pushed those. However, I am not able to reproduce this bug. I.e., on my system I can clone the repository, go to the fusion-operator-presentation folder, type make and the slides build.

I shall look into a way of producing that figure without div(), in any case.

**Comment by gwtaylor** [comment]
Confirming that an update to TeX Live 2018 (via MacTeX 2018) fixed the issues.
